spring.application.name=local-shop-ordering

# MongoDB Connection
spring.data.mongodb.uri=mongodb://localhost:27017/localshopordering
spring.data.mongodb.database=localshopordering

# Disable SQL Configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# For mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amanrajtiu.ac.in@gmail.com
spring.mail.password=ajhe keug yhay uoiv

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true